import Header from "@/components/shared/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }) {
  return <>
        <Header></Header>
        <main>
            {children}
        </main>
  </>
}
